name: Jekyll Deploy on Self-Hosted

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [ self-hosted, ubuntu-latest ]  
    steps:
      - uses: actions/checkout@v3
      

      - name: Install Ruby dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libreadline-dev zlib1g-dev git
          git clone https://github.com/rbenv/ruby-build.git /tmp/ruby-build
          sudo /tmp/ruby-build/install.sh
      
      - name: Build Ruby
        run: |
          sudo mkdir -p /opt/hostedtoolcache/Ruby/3.1.4/x64
          sudo ruby-build 3.1.4 /opt/hostedtoolcache/Ruby/3.1.4/x64
          sudo touch /opt/hostedtoolcache/Ruby/3.1.4/x64.complete

      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      
      - name: Build Jekyll
        run: |
          bundle install
          bundle exec jekyll build